const models = {
    "ch_cube":[
        [
            [['green'],['yellow'],['green']],
            [['yellow'],['green'],['yellow']],
            [['green'],['yellow'],['green']]
        ],
        [
            [['yellow'],['red'],['yellow']],
            [['red'],['yellow'],['red']],
            [['yellow'],['red'],['yellow']]
        ],
        [
            [['red'],['green'],['red']],
            [['green'],['red'],['green']],
            [['red'],['green'],['red']]
        ]
    ],
    "pointer":[
        [
            [[],[],[]],
            [[],["#2196F3"],[]],
            [[],[],[]]
        ],
        [
            [[],["#FFC107"],[]],
            [["#C2185B"],[],["#E91E63"]],
            [[],["#FFA000"],[]]
        ],
        [
            [[],[],[]],
            [[],["#1976D2"],[]],
            [[],[],[]]
        ]
    ]
}